### ISSUE TITLE
Links to official halo api documentation are invalid

### ISSUE THREAD

**Issue by EthanGrahn** [EthanGrahn/halo-api#5]
The official link naming must have changed. Links to official halo api within our own documentation are invalid.
### Example
current:
https://developer.haloapi.com/docs/services/58acdf27e2f7f71ad0dad84b/operations/58acdf28e2f7f70db4854b36
actual:
https://developer.haloapi.com/docs/services/58acdf27e2f7f71ad0dad84b/operations/Halo-5-PC-Match-Result-Custom?

**Comment by JoseLRiano** [comment]
I would like to help solve this issue.
